#     ______                      __  __       _
#    |  ____|                    |  \/  |     | |
#    | |__ _ __ ___ _______ _ __ | \  / | ___ | |__  ___
#    |  __| '__/ _ \_  / _ \ '_ \| |\/| |/ _ \| '_ \/ __|
#    | |  | | | (_) / /  __/ | | | |  | | (_) | |_) \__ \
#    |_|  |_|  \___/___\___|_| |_|_|  |_|\___/|_.__/|___/
#
#                       Version 1.0


# This is used to make sure the config file is up to date.
# Only modify when all necessary additions are made!
configVersion: 1


# -----------------------------------
#              Theme
# -----------------------------------

# Theme modifies the colors for all text
# used by the plugin that cannot be modified
# under Messages.

# Default: "&2"
color1: "&2"

# Default: "&a"
color2: "&a"

# Default: "&8"
color3: "&8"

# -----------------------------------
#            Settings
# -----------------------------------

# When true, mobs do damage
DoDamage: false

# When true, players can do damage to frozen mobs.
PlayerDoDamage: true

# Sets whether or not the mob collides
# with other entities.
Collidable: true

# -----------------------------------
#              Animals
# -----------------------------------

# Toggles which animals are effected.
BAT: true
CAT: true
CHICKEN: true
COD: true
COW: true
DOLPHIN: true
DONKEY: true
FOX: true
HORSE: true
LLAMA: true
MUSHROOM_COW: true
MULE: true
OCELOT: true
PANDA: true
PARROT: true
PIG: true
POLAR_BEAR: true
PUFFERFISH: true
RABBIT: true
SALMON: true
SHEEP: true
SQUID: true
TROPICAL_FISH: true
TURTLE: true
VILLAGER: true
WOLF: true

# -----------------------------------
#              Monsters
# -----------------------------------

# Toggles which monsters are effected.
BLAZE: true
CREEPER: true
DROWNED: true
ENERMITE: true
EVOKER: true
GHAST: true
GUARDIAN: true
HUSK: true
MAGMA_CUBE: true
PHANTOM: true
PILLAGER: true
RAVAGER: true
SHULKER: true
SILVERFISH: true
SKELETON: true
SLIME: true
STRAY: true
VEX: true
VINDICATOR: true
WITCH: true
WITHER_SKELETON: true
ZOMBIE: true
ZOMBIE_VILLAGER: true